// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRApBNSnAcH9Q6G-eAq0XX5gJ5rtMd15U',
    appId: '1:9799442059:android:17c870343f5c557c81be8e',
    messagingSenderId: '9799442059',
    projectId: 'projeto-4-1d471',
    storageBucket: 'projeto-4-1d471.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcgfEVOAmnXxp3uXrzdvT8ipjY2R3p_bU',
    appId: '1:9799442059:web:2fb298f00baad5e281be8e',
    messagingSenderId: '9799442059',
    projectId: 'projeto-4-1d471',
    authDomain: 'projeto-4-1d471.firebaseapp.com',
    storageBucket: 'projeto-4-1d471.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcgfEVOAmnXxp3uXrzdvT8ipjY2R3p_bU',
    appId: '1:9799442059:web:801d418cc78446bd81be8e',
    messagingSenderId: '9799442059',
    projectId: 'projeto-4-1d471',
    authDomain: 'projeto-4-1d471.firebaseapp.com',
    storageBucket: 'projeto-4-1d471.firebasestorage.app',
  );

}